name: test-action
description: "Test action"
outputs:
  foo: 
    value: ${{ steps.output-step.outputs.this-is-output }}
    description: > 
      "Output description"
runs:
  using: composite
  steps:
    - id: step_1
      name: step 1
      run: echo "Your repo is $(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')"
      shell: bash
    - id: output-step
      name: output step
      run: echo "this-is-output=$(echo '')" >> $GITHUB_OUTPUT
      shell: bash